module.exports = {
  apps: [
    {
      name: "hvip-hub",
      script: "dist/hub-server.js",
      args: "--port 9321 --host 127.0.0.1 --web-port 3000",
      cwd: __dirname,
      autorestart: true,
      max_restarts: 50,
      restart_delay: 5000,
      max_memory_restart: "500M",
      log_date_format: "HH:mm:ss",
      error_file: ".hub/logs/hub-error.log",
      out_file: ".hub/logs/hub-out.log",
      max_size: "2M",
      merge_logs: true,
      env: {
        NODE_ENV: "production",
      },
    },
    {
      name: "hvip-mcp",
      script: "dist/index.js",
      args: "start:http",
      cwd: __dirname,
      autorestart: true,
      max_restarts: 5,
      restart_delay: 3000,
      max_memory_restart: "300M",
      log_date_format: "HH:mm:ss",
      error_file: ".hub/logs/mcp-error.log",
      out_file: ".hub/logs/mcp-out.log",
      max_size: "1M",
      merge_logs: true,
      env: {
        NODE_ENV: "production",
        PORT: "9222",
      },
    },
    {
      name: "ai-trader",
      script: "dist/ai-trader.js",
      cwd: __dirname,
      autorestart: true,
      max_restarts: 5,
      restart_delay: 10000,
      max_memory_restart: "300M",
      log_date_format: "HH:mm:ss",
      error_file: ".hub/logs/ai-trader-error.log",
      out_file: ".hub/logs/ai-trader-out.log",
      max_size: "1M",
      merge_logs: true,
      env: {
        NODE_ENV: "production",
        TRADER_INTERVAL: "3600000",
      },
    },
    {
      name: "worker-v2-01",
      script: "dist/hub-worker-v2.js",
      cwd: __dirname,
      autorestart: true,
      max_restarts: 5,
      restart_delay: 5000,
      max_memory_restart: "300M",
      log_date_format: "HH:mm:ss",
      error_file: ".hub/logs/worker2-01-error.log",
      out_file: ".hub/logs/worker2-01-out.log",
      max_size: "1M",
      merge_logs: true,
      env: {
        NODE_ENV: "production",
        HUB_URL: "wss://mcp.hvip.one/ws",
        WORKER_NAME: "Worker·Atlas",
        WORKER_PROFILE: "code",
        WORKER_MAX_TOKENS: "8000",
        WORKER_MAX_STEPS: "15",
      },
    },
    {
      name: "worker-v2-02",
      script: "dist/hub-worker-v2.js",
      cwd: __dirname,
      autorestart: true,
      max_restarts: 5,
      restart_delay: 5000,
      max_memory_restart: "300M",
      log_date_format: "HH:mm:ss",
      error_file: ".hub/logs/worker2-02-error.log",
      out_file: ".hub/logs/worker2-02-out.log",
      max_size: "1M",
      merge_logs: true,
      env: {
        NODE_ENV: "production",
        HUB_URL: "wss://mcp.hvip.one/ws",
        WORKER_NAME: "Worker·Hermes",
        WORKER_PROFILE: "quant",
        WORKER_MAX_TOKENS: "8000",
        WORKER_MAX_STEPS: "15",
      },
    },
    {
      name: "chronos-dispatcher",
      script: "dist/chronos-dispatcher.js",
      cwd: __dirname,
      autorestart: true,
      max_restarts: 5,
      restart_delay: 5000,
      max_memory_restart: "300M",
      log_date_format: "HH:mm:ss",
      error_file: ".hub/logs/chronos-error.log",
      out_file: ".hub/logs/chronos-out.log",
      max_size: "1M",
      merge_logs: true,
      env: {
        NODE_ENV: "production",
        HUB_URL: "wss://mcp.hvip.one/ws",
        HUB_API_URL: "https://mcp.hvip.one",
        CHRONOS_INTERVAL: "60000",
        CHRONOS_PATROL_INTERVAL: "300000",
      },
    },
    {
      name: "hvip-chat",
      script: "server.js",
      cwd: __dirname + "/chat-server",
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      max_memory_restart: "200M",
      log_date_format: "HH:mm:ss",
      error_file: ".hub/logs/chat-error.log",
      out_file: ".hub/logs/chat-out.log",
      max_size: "1M",
      merge_logs: true,
      env: {
        NODE_ENV: "production",
        CHAT_PORT: "3100",
        MCP_URL: "http://127.0.0.1:9222/mcp",
      },
    },
    {
      name: "mcp-gateway",
      script: "dist/mcp-gateway.js",
      args: "--port 9320 --mcp http://127.0.0.1:9222/mcp",
      cwd: __dirname,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      max_memory_restart: "200M",
      log_date_format: "HH:mm:ss",
      error_file: ".hub/logs/gateway-error.log",
      out_file: ".hub/logs/gateway-out.log",
      max_size: "2M",
      merge_logs: true,
      env: {
        NODE_ENV: "production",
        GATEWAY_PORT: "9320",
        MCP_URL: "http://127.0.0.1:9222/mcp",
      },
    },
  ],
};
