/** Agent Catalog — 15 域工具地图. 详见 agent-utils.ts */

export const CATALOG = {
	    _instruction: [
	      "你是 hvip MCP Server 的 AI Agent。收到本目录后，你已经掌握全部必要信息，无需再扫描 tools/list。",
	      "工作流: 1) 看 _setup 了解连接状态和 API Key 配置 → 2) 无Key时优先看 publicDomains（立即可用），有Key时全部可用 → 3) 匹配用户意图到域 → 4) 用 go_to_params 直接调目标工具。",
	      "⚠️ authDomains 中的所有工具需要 API Key——没有 Key 时告诉用户如何配置，不要尝试调用。",
	      "所有 WRITE/FUND_TRANSFER/ADMIN 工具需用户确认后调用，不可自动发起。",
	    ].join(" "),

	    domains: [
	      {
	        domain: "行情看盘",
	        what: "查看产品价格、K线、深度、成交记录",
	        when: ["BTC价格", "ETH行情", "K线", "涨跌", "深度", "盘口", "成交记录", "走势"],
	        go_to: "okx_quick_market",
	        go_to_params: "instId (如 BTC-USDT、ETH-USDT-SWAP)",
	        also: [
	          "okx_get_ticker — 单个产品实时行情",
	          "okx_get_tickers — 某类型全部产品行情",
	          "okx_get_orderbook — 完整深度/盘口",
	          "okx_get_candles — K线数据",
	          "okx_get_trades — 最新成交记录",
	          "okx_get_history_candles — 历史K线",
	          "okx_get_index_candles — 指数K线",
	          "okx_get_mark_price_candles — 标记价K线",
	        ],
	        risk: "READ",
	        authRequired: false,
	      },
	      {
	        domain: "市场扫描",
	        what: "发现市场机会、涨幅榜、跌幅榜、资金费率异常",
	        when: ["今天有什么机会", "涨幅榜", "跌幅榜", "什么在涨", "什么在跌", "异动", "扫描"],
	        go_to: "agent_market_scan",
	        go_to_params: "instType? (默认SWAP), topN? (默认10), sortBy? (change|vol|fundingRate)",
	        also: [
	          "okx_quick_market — 深入看某个品种",
	          "okx_get_funding_rate — 永续合约资金费率",
	          "okx_get_tickers — 全市场行情",
	        ],
	        risk: "READ",
	        authRequired: false,
	      },
	      {
	        domain: "技术指标",
	        what: "技术分析：RSI、MACD、布林带、KDJ、ADX、Supertrend 等 17 种指标 + 信号解读",
	        when: ["RSI", "MACD", "布林带", "KDJ", "ADX", "超买", "超卖", "金叉", "死叉", "技术指标", "指标分析"],
	        go_to: "okx_indicator",
	        go_to_params: "instId, indicator (rsi|macd|bb|atr|stoch 等17种), period?, bar? (默认1H)",
	        also: [
	          "okx_indicator — 单指标计算+信号解读",
	          "okx_indicator_batch — 多指标批量+综合信号（2个工具互备）",
	          "okx_get_candles — 原始K线数据",
	        ],
	        risk: "READ",
	        authRequired: false,
	      },
	      {
	        domain: "模拟估算",
	        what: "不产生真实订单，预估成交价、滑点、手续费、保证金",
	        when: ["如果买入", "如果卖出", "模拟", "预估", "沙盒", "试算", "会怎样"],
	        go_to: "agent_simulate_order",
	        go_to_params: "instId, side (buy|sell), sz, tdMode (cash|cross|isolated), px?",
	        also: [
	          "okx_preflight_check — 下单前参数校验",
	          "okx_position_builder — 组合保证金试算",
	          "agent_quick_trade — 确认后真实下单（WRITE，需Key）",
	        ],
	        risk: "READ",
	        authRequired: false,
	      },
	      {
	        domain: "WebSocket 实时",
	        what: "实时行情推送、爆仓流、价差/大宗数据（公开频道 33 个）",
	        when: ["实时", "订阅", "推送", "websocket", "ws", "监听", "爆仓", "实时行情"],
	        go_to: "okx_ws_subscribe",
	        go_to_params: "instId (产品ID), channel (33个公开频道)",
	        also: [
	          "okx_ws_subscribe_private — 私有频道（账户/持仓/订单，需Key）",
	          "okx_ws_events — 拉取缓冲事件",
	          "okx_ws_status — 查看订阅状态",
	          "okx_ws_close — 关闭订阅",
	        ],
	        risk: "READ",
	        authRequired: false,
	      },
	      {
	        domain: "代码智能",
	        what: "查询 hvip-mcp 自身代码结构：函数调用链、模块依赖、符号搜索",
	        when: ["代码结构", "调用链", "谁调用了", "谁被调用", "依赖关系", "上下游", "代码搜索"],
	        go_to: "codegraph_status",
	        go_to_params: "无需参数",
	        also: [
	          "codegraph_query — 调用链追踪 (callers|callees|search|file|impact)",
	        ],
	        risk: "READ",
	        authRequired: false,
	      },
	      {
	        domain: "系统工具",
	        what: "偏好设置、反馈留言、Agent集群管理、X Layer 链上交互",
	        when: ["偏好", "设置默认", "记住", "反馈", "建议", "Agent Hub", "集群"],
	        go_to: "agent_get_preference",
	        go_to_params: "key? (不填返回全部)",
	        also: [
	          "agent_set_preference — 保存偏好",
	          "okx_agent_feedback — 提交使用反馈",
	          "agent_hub_status — Agent 集群状态",
	          "agent_hub_dispatch — 派发任务",
	          "agent_room_send — 房间消息",
	          "xlayer_subscribe — X Layer 链上事件",
	          "xlayer_call — X Layer 合约调用（WRITE）",
	        ],
	        risk: "READ",
	        authRequired: false,
	      },
	      // ═══════════════════ 以下需要 API Key ═══════════════════
	      {
	        domain: "账户资产",
	        what: "查看账户余额、持仓、配置、手续费、估值",
	        when: ["我的账户", "持仓", "余额", "保证金", "杠杆倍数", "资产估值", "手续费率", "账户配置"],
	        go_to: "okx_account_overview",
	        go_to_params: "无需参数",
	        also: [
	          "okx_get_balance — 各币种余额明细",
	          "okx_get_positions — 持仓详情（含平仓上下文 _actionContext）",
	          "okx_get_account_config — 账户模式/持仓模式",
	          "okx_get_asset_valuation — 总资产估值",
	          "okx_get_fee_rates — 手续费率",
	          "okx_get_leverage_info — 当前杠杆倍数",
	          "okx_get_max_size — 最大可开数量",
	          "okx_set_leverage — 调整杠杆（WRITE，需确认）",
	        ],
	        risk: "READ",
	        authRequired: true,
	      },
	      {
	        domain: "下单交易",
	        what: "下单、撤单、改单、平仓",
	        when: ["买入", "卖出", "下单", "开仓", "平仓", "撤单", "改单", "挂单"],
	        go_to: "agent_quick_trade",
	        go_to_params: "instId, side (buy|sell), sz, tdMode (cash|cross|isolated), px?, ordType? (market|limit)",
	        also: [
	          "okx_preflight_check — 下单前预检（数量/限价/合约换算）",
	          "agent_simulate_order — 模拟下单（不产生真实订单）",
	          "okx_place_order — 标准下单（WRITE，需确认）",
	          "okx_cancel_order — 撤单（WRITE）",
	          "okx_amend_order — 改单（WRITE）",
	          "okx_close_position — 平仓（WRITE，需确认）",
	          "okx_get_order — 查询订单状态",
	          "okx_get_orders_pending — 当前挂单",
	          "okx_get_orders_history — 历史订单",
	          "okx_batch_orders — 批量下单（WRITE）",
	          "okx_batch_cancel_orders — 批量撤单（WRITE）",
	          "okx_amend_batch_orders — 批量改单（WRITE）",
	        ],
	        risk: "WRITE",
	        authRequired: true,
	      },
	      {
	        domain: "风险风控",
	        what: "持仓风险评估、强平预警、保证金率",
	        when: ["风险", "爆仓", "强平", "保证金率", "健康度", "风控", "会不会爆"],
	        go_to: "agent_risk_overview",
	        go_to_params: "无需参数",
	        also: [
	          "okx_get_account_position_risk — 账户持仓风险详情",
	          "okx_get_risk_state — 账户风控状态",
	          "okx_get_positions — 持仓中的 mgnRatio/liqPx",
	          "okx_get_margin_balance — 保证金余额",
	          "agent_quick_trade — 风控告警后平仓（WRITE）",
	        ],
	        risk: "READ",
	        authRequired: true,
	      },
	      {
	        domain: "盈亏复盘",
	        what: "计算已实现/未实现盈亏、交易绩效",
	        when: ["赚了多少", "亏了多少", "盈亏", "绩效", "复盘", "PnL", "收益"],
	        go_to: "agent_pnl_report",
	        go_to_params: "days? (默认7)",
	        also: [
	          "okx_get_positions — 当前浮动盈亏",
	          "okx_get_orders_history — 历史订单盈亏",
	          "okx_get_positions_history — 历史平仓盈亏",
	          "okx_get_fills — 成交明细",
	        ],
	        risk: "READ",
	        authRequired: true,
	      },
	      {
	        domain: "资金管理",
	        what: "划转、提现、充值、兑换",
	        when: ["划转", "提现", "充值", "转账", "兑换", "闪兑", "出入金", "deposit", "withdraw"],
	        go_to: "okx_get_balance",
	        go_to_params: "ccy? (如 BTC，不填全部)",
	        also: [
	          "okx_transfer — 资金划转（WRITE，需确认）",
	          "okx_withdrawal — 提现（WRITE，需确认）",
	          "okx_get_deposit_address — 获取充值地址",
	          "okx_get_deposit_history — 充值记录",
	          "okx_get_withdrawal_history — 提现记录",
	          "okx_convert_trade — 一键兑换（WRITE，需确认）",
	          "okx_get_convert_currencies — 可兑换币种",
	          "okx_get_currencies — 链上币种信息",
	          "okx_get_funding_balance — 资金账户余额",
	        ],
	        risk: "FUND_TRANSFER",
	        authRequired: true,
	      },
	      {
	        domain: "策略交易",
	        what: "网格、跟单、信号、策略委托、价差、RFQ",
	        when: ["网格", "跟单", "信号", "策略", "定投", "价差", "大宗", "RFQ"],
	        go_to: "okx_get_grid_ai_param",
	        go_to_params: "instType (SPOT|SWAP|FUTURES), algoOrdType (grid|contract_grid|recurring_buy|twap|iceberg)",
	        also: [
	          "okx_create_grid_order — 创建网格（WRITE，需确认）",
	          "okx_stop_grid_order — 停止网格",
	          "okx_get_grid_positions — 网格持仓",
	          "okx_create_recurring_plan — 创建定投计划（WRITE）",
	          "okx_copy_trader — 开始跟单（WRITE，需确认）",
	          "okx_get_lead_trader_positions — 交易员持仓",
	          "okx_get_lead_trader_stats — 交易员统计",
	          "okx_place_algo_order — 策略委托下单（WRITE）",
	          "okx_get_algo_orders — 策略委托列表",
	          "okx_create_rfq — 创建大宗询价（WRITE）",
	        ],
	        risk: "WRITE",
	        authRequired: true,
	      },
	      {
	        domain: "聪明钱",
	        what: "交易员排行榜、聪明钱流向、市场情绪分析",
	        when: ["交易员", "排行榜", "聪明钱", "跟谁赚钱", "情绪", "多空比", "恐慌", "smart money"],
	        go_to: "okx_smart_leaderboard",
	        go_to_params: "instType? (SPOT|SWAP), sortBy? (pnl|winRate|sharpe), topN?",
	        also: [
	          "okx_smart_leaderboard — 交易员排行榜",
	          "okx_smart_trader_detail — 单交易员深度分析",
	          "okx_smart_sentiment — 市场情绪仪表盘",
	          "okx_get_lead_trader_positions — 交易员当前持仓",
	          "okx_get_lead_trader_stats — 交易员历史统计",
	        ],
	        risk: "READ",
	        authRequired: true,
	      },
	      {
	        domain: "预测市场",
	        what: "事件合约、预测市场交易（公开查询 + 需Key交易）",
	        when: ["预测市场", "事件合约", "outcomes", "predictions", "对赌"],
	        go_to: "okx_event_instruments",
	        go_to_params: "eventType? (不填返回全部)",
	        also: [
	          "okx_predictions_ticker — 预测市场行情（公开）",
	          "okx_predictions_orderbook — 预测市场深度（公开）",
	          "okx_event_place_order — 事件合约下单（WRITE，需Key）",
	          "okx_event_fills — 事件合约成交（需Key）",
	          "okx_predictions_positions — 预测市场持仓（需Key）",
	          "okx_predictions_order_list — 预测市场订单（需Key）",
	          "okx_predictions_redeem — 预测市场赎回（WRITE，需Key）",
	        ],
	        risk: "READ",
	        authRequired: true,
	      },
	    ],

	    _tips: [
	      "每个新会话先调 agent_get_preference 恢复用户偏好(默认交易对/风险偏好/仓位占比)",
	      "需要 API Key 时告诉用户去 OKX 官网创建，开通读取+交易权限",
	      "先模拟后交易: agent_simulate_order 预估 -> 确认 -> agent_quick_trade 下单",
	      "WRITE 工具会修改账户，调用前必须向用户确认，不可自动发起",
	      "技术指标用 okx_indicator 单个计算或 okx_indicator_batch 批量，支持 RSI/MACD/布林带等 17 种",
	      "无 Key 想看盘: okx_quick_market 看行情 + okx_indicator 看指标 + agent_market_scan 扫市场",
	    ],
	  }
