/** 域工具详情 — sys_catalog_detail 使用. 详见 agent-utils.ts */

export const DOMAIN_DETAILS: Record<string, any> = {
    "账户资产": { authRequired: true,
      workflow: "account_overview（全景）→ 查看具体项 → account_balance / account_positions 细化",
      tools: [
        { name: "account_overview", auth: "API Key", params: "无", what: "账户全景：余额+持仓+配置+估值 四合一一键查询" },
        { name: "account_balance", auth: "API Key", params: "ccy? (币种，不填全部)", what: "交易账户各币种余额" },
        { name: "account_positions", auth: "API Key", params: "instType? (不填全部)", what: "持仓详情，含 _actionContext 可直接用于平仓" },
        { name: "account_config", auth: "API Key", params: "无", what: "账户模式/持仓模式/UID" },
        { name: "account_valuation", auth: "API Key", params: "ccy? (计价币种)", what: "总资产估值" },
        { name: "account_fee_rates", auth: "API Key", params: "instType?, instId?", what: "手续费率" },
        { name: "account_leverage", auth: "API Key", params: "instId, mgnMode", what: "当前杠杆倍数" },
        { name: "trade_max_size", auth: "API Key", params: "instId, tdMode", what: "最大可开仓数量" },
        { name: "account_leverage_set", auth: "API Key (交易)", params: "instId, lever, mgnMode", what: "调整杠杆 — WRITE，需确认" },
        { name: "account_max_loan", auth: "API Key", params: "instId, mgnMode", what: "最大可借数量" },
        { name: "account_margin_balance", auth: "API Key", params: "instId, mgnMode", what: "保证金余额详情" },
        { name: "account_position_mode_set", auth: "API Key (交易)", params: "posMode", what: "切换持仓模式 — ADMIN，需确认" },
        { name: "account_bills", auth: "API Key", params: "instType?, ccy?, limit?", what: "账户资金流水" },
        { name: "account_interest_accrued", auth: "API Key", params: "instId?, ccy?", what: "借币利息累计" },
        { name: "account_interest_rates", auth: "API Key", params: "ccy?", what: "各币种借币利率" },
        { name: "account_interest_limits", auth: "API Key", params: "无", what: "利息限额" },
        { name: "account_max_withdrawal", auth: "API Key", params: "ccy?", what: "最大可提现数量" },
        { name: "account_position_risk", auth: "API Key", params: "无", what: "持仓风险评估" },
        { name: "risk_state", auth: "API Key", params: "无", what: "账户风控状态" },
        { name: "account_greeks", auth: "API Key", params: "instType?, instFamily?", what: "期权 Greeks 风险参数" },
        { name: "account_trade_fee", auth: "API Key", params: "instType?, instId?", what: "按产品维度查询手续费" },
        { name: "account_convert_currencies", auth: "API Key", params: "无", what: "支持一键兑换的币种列表" },
        { name: "account_convert_trade", auth: "API Key (交易)", params: "fromCcy, toCcy, sz", what: "执行资产兑换 — FUND_TRANSFER，需确认" },
        { name: "account_bills_detail", auth: "API Key", params: "instType?, ccy?", what: "账户账单流水" },
        { name: "account_positions_history", auth: "API Key", params: "instType?, instId?", what: "历史持仓（已平仓）" },
        { name: "account_bills_archive", auth: "API Key", params: "无", what: "归档账单（3个月前）" },
        { name: "account_borrow_repay", auth: "API Key (交易)", params: "ccy, side(borrow|repay), amt", what: "借币/还款 — FUND_TRANSFER，需确认" },
        { name: "account_borrow_repay_history", auth: "API Key", params: "无", what: "借贷历史记录" },
        { name: "account_option_activate", auth: "API Key (交易)", params: "无", what: "激活期权交易 — ADMIN，需确认" },
        { name: "account_mode_set", auth: "API Key (交易)", params: "acctLv(1|2|3|4)", what: "设置账户层级 — ADMIN，需确认" },
      ],
    },
    "行情看盘": { authRequired: false,
      workflow: "market_quick（速览）→ 需要K线时调 market_candles → 需要全深度时调 market_orderbook",
      tools: [
        { name: "market_quick", auth: "公开", params: "instId", what: "行情+5档深度+资金费率 三合一速览" },
        { name: "market_ticker", auth: "公开", params: "instId", what: "单个产品最新行情" },
        { name: "market_tickers", auth: "公开", params: "instType", what: "某类型全部产品行情" },
        { name: "market_orderbook", auth: "公开", params: "instId, sz?", what: "订单簿深度（默认1档，最大400档）" },
        { name: "market_orderbook_full", auth: "公开", params: "instId", what: "全量订单簿" },
        { name: "market_candles", auth: "公开", params: "instId, bar, limit?", what: "K线数据" },
        { name: "market_candles_history", auth: "公开", params: "instId, bar, after?", what: "历史K线（更早的）" },
        { name: "market_index_candles", auth: "公开", params: "instId, bar", what: "指数K线" },
        { name: "market_mark_candles", auth: "公开", params: "instId, bar", what: "标记价K线" },
        { name: "market_trades", auth: "公开", params: "instId, limit?", what: "最新成交记录" },
        { name: "market_trades_history", auth: "公开", params: "instId, after?", what: "历史成交记录" },
        { name: "market_index_tickers", auth: "公开", params: "quoteCcy?", what: "指数行情" },
        { name: "market_block_tickers", auth: "公开", params: "instType", what: "批量产品行情（Tickers）" },
        { name: "market_mark_price", auth: "公开", params: "instType?, instId?", what: "标记价格" },
        { name: "market_funding_rate", auth: "公开", params: "instId", what: "永续合约当前资金费率" },
        { name: "market_funding_rate_history", auth: "公开", params: "instId, before?, after?", what: "资金费率历史" },
      ],
    },
    "下单交易": { authRequired: true,
      workflow: "先调 sim_order 预估 → 再调 trade_preflight 校验 → 最后 trade_quick 下单",
      tools: [
        { name: "trade_quick", auth: "API Key (交易)", params: "instId, side, sz, tdMode, px?, ordType?", what: "一键下单全流程 — WRITE，需确认" },
        { name: "sim_order", auth: "API Key (只读)", params: "instId, side, sz, tdMode, px?", what: "模拟下单：滑点/手续费/成本预估（无真实订单）" },
        { name: "trade_preflight", auth: "API Key (只读)", params: "instId, tdMode, sz, px?, side?, ordType?", what: "下单前预检：数量/限价/合约换算" },
        { name: "trade_place", auth: "API Key (交易)", params: "instId, tdMode, side, sz, ordType, px?", what: "标准下单 — WRITE，需确认" },
        { name: "trade_place_batch", auth: "API Key (交易)", params: "orders[]", what: "批量下单 — WRITE" },
        { name: "trade_cancel", auth: "API Key (交易)", params: "instId, ordId", what: "撤销单笔订单 — WRITE" },
        { name: "trade_cancel_batch", auth: "API Key (交易)", params: "orders[]", what: "批量撤单 — WRITE" },
        { name: "trade_amend", auth: "API Key (交易)", params: "instId, ordId, newSz?, newPx?", what: "修改未成交订单 — WRITE" },
        { name: "trade_amend_batch", auth: "API Key (交易)", params: "orders[]", what: "批量改单 — WRITE" },
        { name: "trade_close", auth: "API Key (交易)", params: "instId, posSide, mgnMode", what: "平仓（用 _actionContext 中参数）— WRITE，需确认" },
        { name: "trade_order", auth: "API Key", params: "instId, ordId", what: "查询单笔订单状态" },
        { name: "trade_orders_active", auth: "API Key", params: "instType?, instId?", what: "当前挂单列表" },
        { name: "account_orders_history", auth: "API Key", params: "instType, limit?", what: "历史订单（近3个月）" },
        { name: "trade_fills", auth: "API Key", params: "instType?, instId?, ordId?", what: "最近成交明细" },
        { name: "trade_fills_history", auth: "API Key", params: "instType?, instId?, limit?", what: "历史成交明细" },
      ],
    },
    "风险风控": { authRequired: true,
      workflow: "risk_overview（全景）→ 发现风险仓位 → trade_quick 平仓",
      tools: [
        { name: "risk_overview", auth: "API Key", params: "无", what: "全仓风险仪表盘：风险排序+强平预警+保证金率" },
        { name: "account_position_risk", auth: "API Key", params: "无", what: "账户持仓风险详情" },
        { name: "risk_state", auth: "API Key", params: "无", what: "账户风控状态" },
        { name: "account_margin_balance", auth: "API Key", params: "instId, mgnMode", what: "某产品的保证金余额" },
        { name: "account_positions", auth: "API Key", params: "instType?", what: "持仓中的 liqPx/mgnRatio 字段可直接评估风险" },
        { name: "account_max_withdrawal", auth: "API Key", params: "ccy?", what: "最大可提现额度" },
      ],
    },
    "市场扫描": { authRequired: false,
      workflow: "scan_market（异动）→ market_quick（深入）→ 下单",
      tools: [
        { name: "scan_market", auth: "公开", params: "instType?, topN?, sortBy?", what: "涨幅榜/跌幅榜/成交量/资金费率异常一键扫描" },
        { name: "market_tickers", auth: "公开", params: "instType", what: "某类型全部产品行情（可自行排序过滤）" },
        { name: "market_funding_rate", auth: "公开", params: "instId", what: "单产品资金费率" },
        { name: "market_funding_rate_history", auth: "公开", params: "instId", what: "资金费率历史趋势" },
      ],
    },
    "盈亏复盘": { authRequired: true,
      workflow: "pnl_report（盈亏报告）→ 需要时查 trade_fills 明细",
      tools: [
        { name: "pnl_report", auth: "API Key", params: "days?", what: "浮动盈亏+已实现盈亏 双维日报" },
        { name: "account_positions", auth: "API Key", params: "instType?", what: "当前持仓浮动盈亏" },
        { name: "account_positions_history", auth: "API Key", params: "instType?, instId?", what: "历史平仓盈亏" },
        { name: "account_orders_history", auth: "API Key", params: "instType", what: "历史订单盈亏" },
        { name: "trade_fills", auth: "API Key", params: "instType?, instId?", what: "逐笔成交明细（可按 pnl 字段求和）" },
      ],
    },
    "资金管理": { authRequired: true,
      workflow: "先看余额 → 再决定划转/提现/充值",
      tools: [
        { name: "account_balance", auth: "API Key", params: "ccy?", what: "交易账户余额" },
        { name: "fund_balance", auth: "API Key", params: "ccy?", what: "资金账户余额" },
        { name: "fund_transfer", auth: "API Key (交易)", params: "ccy, amt, from, to", what: "资金划转 — FUND_TRANSFER，需确认" },
        { name: "fund_transfer_state", auth: "API Key", params: "transId?", what: "划转状态查询" },
        { name: "fund_withdraw", auth: "API Key (交易)", params: "ccy, amt, dest, toAddr", what: "提现 — FUND_TRANSFER，需确认" },
        { name: "fund_deposit_address", auth: "API Key", params: "ccy", what: "获取充值地址" },
        { name: "fund_deposit_history", auth: "API Key", params: "ccy?, limit?", what: "充值记录" },
        { name: "fund_withdrawal_history", auth: "API Key", params: "ccy?, limit?", what: "提现记录" },
        { name: "fund_currencies", auth: "API Key", params: "ccy?", what: "链上币种信息" },
        { name: "account_convert_trade", auth: "API Key (交易)", params: "fromCcy, toCcy, sz", what: "一键兑换 — FUND_TRANSFER，需确认" },
        { name: "account_convert_currencies", auth: "API Key", params: "无", what: "可兑换币种列表" },
        { name: "account_max_withdrawal", auth: "API Key", params: "ccy?", what: "最大可提现数量" },
        { name: "fund_non_tradable_assets", auth: "API Key", params: "ccy?", what: "不可交易资产" },
        { name: "fund_exchange_list", auth: "API Key", params: "无", what: "交易所列表" },
        { name: "fund_deposit_withdraw_status", auth: "API Key", params: "无", what: "充提状态" },
      ],
    },
    "策略交易": { authRequired: true,
      workflow: "网格/跟单/信号/策略委托 各自独立，按需调用",
      tools: [
        { name: "strategy_grid_ai_params", auth: "API Key", params: "instType, algoOrdType", what: "网格AI参数推荐" },
        { name: "strategy_grid_create", auth: "API Key (交易)", params: "instId, algoOrdType, maxPx, minPx, gridNum, sz", what: "创建网格 — WRITE" },
        { name: "strategy_grid_stop", auth: "API Key (交易)", params: "algoId, instId, algoOrdType, stopType", what: "停止网格" },
        { name: "strategy_grid_close", auth: "API Key (交易)", params: "algoId, mktClose", what: "平仓网格所有持仓" },
        { name: "strategy_grid_positions", auth: "API Key (交易)", params: "algoOrdType, algoId?", what: "网格持仓" },
        { name: "strategy_grid_sub_orders", auth: "API Key", params: "algoId, algoOrdType, type", what: "网格子订单" },
        { name: "strategy_grid_orders_active", auth: "API Key", params: "algoOrdType, algoId?", what: "运行中的网格" },
        { name: "strategy_grid_orders_history", auth: "API Key", params: "algoOrdType, algoId?", what: "历史网格" },
        { name: "strategy_recurring_create", auth: "API Key (交易)", params: "instId, sz, period, recurringList", what: "定投计划 — WRITE" },
        { name: "strategy_recurring_stop", auth: "API Key (交易)", params: "algoId", what: "停止定投" },
        { name: "strategy_copy_start", auth: "API Key (交易)", params: "uniqueCode, copyTotalAmt, instType", what: "开始跟单 — WRITE，需确认" },
        { name: "strategy_copy_traders", auth: "API Key", params: "无", what: "我关注的交易员" },
        { name: "strategy_copy_public_leaders", auth: "公开", params: "instType, sortType?", what: "公开交易员列表" },
        { name: "strategy_copy_lead_positions", auth: "API Key", params: "uniqueCode", what: "交易员当前持仓" },
        { name: "strategy_copy_lead_stats", auth: "API Key", params: "uniqueCode", what: "交易员业绩统计" },
        { name: "strategy_algo_place", auth: "API Key (交易)", params: "instId, tdMode, side, ordType, sz, triggerPx", what: "策略委托下单 — WRITE" },
        { name: "strategy_algo_orders", auth: "API Key", params: "ordType?, algoId?", what: "策略委托列表" },
        { name: "strategy_algo_cancel", auth: "API Key (交易)", params: "algoId, instId", what: "撤销策略委托 — WRITE" },
      ],
    },
    "预测市场": { authRequired: true,
      workflow: "predict_event_instruments 看市场 → predict_event_place 下单",
      tools: [
        { name: "predict_event_instruments", auth: "公开", params: "eventType?", what: "事件合约产品列表" },
        { name: "predict_event_place", auth: "API Key (交易)", params: "instId, side, sz, ordType?", what: "事件合约下单 — WRITE" },
        { name: "predict_event_cancel", auth: "API Key (交易)", params: "instId, ordId", what: "事件合约撤单 — WRITE" },
        { name: "predict_event_amend", auth: "API Key (交易)", params: "instId, ordId, newSz?", what: "事件合约改单 — WRITE" },
        { name: "predict_event_fills", auth: "API Key", params: "instId?", what: "事件合约成交记录" },
        { name: "predict_place", auth: "API Key (交易)", params: "marketId, side, price, size", what: "预测市场下单 — WRITE" },
        { name: "predict_positions", auth: "API Key", params: "marketId?", what: "预测市场持仓" },
        { name: "predict_orders", auth: "API Key", params: "marketId?, status?", what: "预测市场订单列表" },
        { name: "predict_redeem", auth: "API Key (交易)", params: "marketId, outcome", what: "预测市场赎回 — WRITE" },
        { name: "predict_balance", auth: "API Key", params: "无", what: "预测市场余额" },
      ],
    },
    "技术指标": { authRequired: false,
      workflow: "indicator_calc 单指标计算 → 需要综合判断时 indicator_calc_batch 批量计算",
      tools: [
        { name: "indicator_calc", auth: "公开", params: "instId, indicator, period?, bar?", what: "单指标计算+Agent信号解读（17种指标含RSI/MACD/BB/ATR/ADX等）" },
        { name: "indicator_batch", auth: "公开", params: "instId, indicators(逗号分隔), bar?", what: "多指标批量计算+综合信号共识（最多10个指标）" },
      ],
    },
    "聪明钱": { authRequired: true,
      workflow: "smart_leaderboard 看排行 → smart_trader_detail 深挖 → smart_sentiment 看情绪",
      tools: [
        { name: "smart_leaderboard", auth: "公开", params: "instType?, sortBy?, topN?", what: "交易员排行榜（按收益率/总收益/跟单人数排序）" },
        { name: "smart_trader_detail", auth: "公开", params: "uniqueCode, instType?", what: "单交易员全景：收益率+胜率+回撤+持仓+PnL曲线" },
        { name: "smart_sentiment", auth: "公开", params: "instFamily?", what: "市场情绪仪表盘：多空比+PCR+资金费率 → 量化评分(0-100)" },
      ],
    },
    "WebSocket 实时": { authRequired: false,
      workflow: "ws_subscribe 公开频道 → ws_subscribe_private 私有频道（需Key）→ ws_events 拉取 → ws_status 管理",
      tools: [
        { name: "ws_subscribe", auth: "公开", params: "instId, channel (33公开频道)", what: "订阅公开频道：行情/深度/爆仓/价差/大宗/资金费率等" },
        { name: "ws_subscribe_private", auth: "API Key", params: "instId?, channel (22私有频道)", what: "订阅私有频道：账户/持仓/订单/网格/跟单等实时推送" },
        { name: "ws_events", auth: "公开", params: "subscriptionId?, limit?, filter?", what: "拉取缓冲的实时事件" },
        { name: "ws_status", auth: "公开", params: "无", what: "当前所有订阅+缓冲积压" },
        { name: "ws_close", auth: "公开", params: "subscriptionId?", what: "关闭订阅" },
      ],
    },
    "模拟估算": { authRequired: false,
      workflow: "sim_order（预估）→ 用户确认 → trade_quick（真实下单）",
      tools: [
        { name: "sim_order", auth: "API Key (只读)", params: "instId, side, sz, tdMode, px?", what: "模拟下单：成交价/滑点/手续费/资金占用 全预估" },
        { name: "trade_preflight", auth: "API Key (只读)", params: "instId, tdMode, sz, px?, side?, ordType?", what: "下单预检：最大可开/限价/合约换算" },
        { name: "account_position_builder", auth: "API Key (交易)", params: "body(JSON)", what: "组合保证金试算 — WRITE" },
      ],
    },
    "代码智能": { authRequired: false,
      workflow: "code_status 看状态 → code_query 追踪调用链/搜索符号 → 用 Read 看源码细节",
      tools: [
        { name: "code_status", auth: "公开", params: "无", what: "知识图谱状态：节点数/边数/覆盖文件/最后索引" },
        { name: "code_query", auth: "公开", params: "mode (callers|callees|explore|files), symbol?, question?, limit?", what: "查询调用链 / 符号搜索 / 模块依赖 / 按文件查" },
      ],
    },
    "系统工具": { authRequired: false,
      workflow: "按需调用，各工具独立",
      tools: [
        { name: "sys_catalog", auth: "公开", params: "无", what: "你正在看的这个" },
        { name: "sys_catalog_detail", auth: "公开", params: "domain", what: "查看某个域的详细工具清单" },
        { name: "sys_preference", auth: "公开", params: "key?", what: "读取 Agent 持久化偏好" },
        { name: "sys_preference_set", auth: "公开", params: "key, value", what: "保存 Agent 偏好" },
        { name: "sys_feedback", auth: "公开", params: "title, what, tools, pain, suggestion", what: "提交使用反馈" },
        { name: "sys_hub_status", auth: "公开", params: "无", what: "Agent 集群状态" },
        { name: "sys_hub_dispatch", auth: "公开", params: "taskId, agentId?", what: "派发任务给 Agent" },
        { name: "sys_hub_review", auth: "公开", params: "taskId, verdict, feedback?", what: "审核 Agent 提交结果" },
        { name: "sys_room_send", auth: "公开", params: "roomId, text", what: "发送房间消息" },
        { name: "sys_room_view", auth: "公开", params: "roomId?, limit?", what: "查看房间消息历史" },
        { name: "ws_ws_xlayer_subscribe", auth: "公开", params: "channel, address?", what: "X Layer 链上事件订阅" },
        { name: "ws_ws_xlayer_call", auth: "公开", params: "to, data, value?", what: "X Layer 合约调用 — WRITE" },
        { name: "ws_xlayer_events", auth: "公开", params: "channel?", what: "X Layer 链上事件" },
        { name: "sys_status", auth: "公开", params: "无", what: "OKX 系统状态" },
        { name: "market_instruments", auth: "公开", params: "instType, instId?", what: "产品列表/详情" },
      ],
    },
  }
